---
- hosts: all
  gather_facts: no
  vars_files:
    - ../settings.yml

  tasks:
    - name: Create ansible inventory file.
      template: src=templates/hosts.j2 dest={{ inventory_file }}
      delegate_to: 127.0.0.1

    - name: Remove reference of host from local hosts file.
      lineinfile:
        dest={{ hosts_file }}
        state=absent
        regexp="{{ ip }}\s*{{ webserver_servername }} {{ webserver_serveralias }}"
      delegate_to: 127.0.0.1
      sudo: true

    - name: Add reference of host to local hosts file.
      lineinfile:
        dest={{ hosts_file }}
        state=present
        line="{{ ip }} {{ webserver_servername }} {{ webserver_serveralias }}"
        create=yes
      delegate_to: 127.0.0.1
      sudo: true
