---
- hosts: all
  gather_facts: no
  vars_files:
    - ../settings.yml

  tasks:
    - name: Delete ansible inventory file.
      file: path={{ inventory_file }} state=absent
      delegate_to: 127.0.0.1

    - name: Remove reference of host from local hosts file.
      lineinfile:
        dest={{ hosts_file }}
        state=absent
        regexp="{{ ip }}\s*{{ webserver_servername }} {{ webserver_serveralias }}"
      delegate_to: 127.0.0.1
      sudo: true
