---

# Vagrantfile configuration.
box: 'chef/centos-6.5'
hostname: 'vagrant-lamp'
ip: '192.168.10.10'
synced_folder: './www'

# Webserver configuration.
webserver_servername: 'drupal7.dev'
webserver_serveralias: 'www.drupal7.dev'

# Local hosts file location.
hosts_file: '/etc/hosts'

# Git configuration.
git_user_name: "YOUR_FULLNAME_HERE"
git_user_email: "YOUR_EMAIL_HERE"

# Ansible verbose mode.
ansible_verbose: ''

# MySQL configurations.
mysql_root_password: 'root'
mysql_port: 3306
